version: '3.3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: masterkey
      DB_NAME: spring-caching
      DB_USER: user
      DB_PASSWORD: masterkey
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"